nodeLinker: node-modules
npmMinimalAgeGate: 10080
npmPreapprovedPackages:
  - expo
  - expo-*
  - "@expo/*"
  - babel-preset-expo
  - react-native
  - "@react-native/*"
  - storybook
  - "@storybook/*"
  - eslint-plugin-storybook
  - "@chromatic-com/storybook"
  - create-storybook
  - sb
