nodeLinker: node-modules
npmMinimalAgeGate: 10080
npmPreapprovedPackages:
  - next
  - "@next/*"
  - eslint-config-next
  - "@tailwindcss/turbopack"
  - storybook
  - "@storybook/*"
  - eslint-plugin-storybook
  - "@chromatic-com/storybook"
  - create-storybook
  - sb
